@startuml Diagrama

    Class Usuario
    Class Tamagotchi
    Class Pantalla
    Class Boton
    Class Kirby
    Class Personaje
    Class Juego
    Class Comida
    Class Siesta
    Class Actividad
    Class Salida
    Class Vida
    Class Muerte
    
    Usuario "1" o-- "1" Tamagotchi
    Tamagotchi "1" *-- "1" Pantalla
    Tamagotchi "1" *-- "2" Boton
    Tamagotchi "1" *-- "1" Kirby

    Usuario "1" o-- "2" Boton
    Boton "1" o-- "3" Juego
    Boton "1" o-- "1" Salida
    Kirby "1" *-- "1" Vida
    Pantalla "1" *-- "1" Kirby
    
    Kirby --|> Personaje
    Salida --|> Muerte
    Comida --|> Juego
    Siesta --|> Juego
    Actividad --|> Juego
    

@enduml