@startuml Diagrama

    Class Usuario
    Class Tamagotchi
    Class Pantalla
    Class Boton
    Class Juan
    Class Juego
    Class Comida
    Class Siesta
    Class Actividad
    Class Salida
    Class Muerte
    
    Usuario "1" o-- "1" Tamagotchi
    Usuario "1" o-- "1" Salida
    Tamagotchi "1" *-- "1" Pantalla
    Tamagotchi "1" *-- "3" Boton
    Tamagotchi "1" *-- "1" Juan

    Juan "1" o-- "1" Pantalla
    Juan "1" o-- "3" Juego

    Comida --|> Juego
    Siesta --|> Juego
    Actividad --|> Juego
    Salida --|> Muerte

@enduml